"use client";
import { useMemo, useState } from "react";
const GIB=1024**3,TIB=1024**4,KIB256=256*1024;
type Raid="stripe"|"mirror"|"raidz1"|"raidz2"|"raidz3";
const raidInfo:Record<Raid,{label:string;parity:number}>={stripe:{label:"Stripe (no redundancy)",parity:0},mirror:{label:"Mirror",parity:0},raidz1:{label:"RAIDZ1",parity:1},raidz2:{label:"RAIDZ2",parity:2},raidz3:{label:"RAIDZ3",parity:3}};
const clamp=(n:number,min=0)=>Number.isFinite(n)?Math.max(min,n):min;
const fmt=(b:number)=>`${(b/TIB).toLocaleString(undefined,{maximumFractionDigits:2})} TiB`;
const fmtTB=(b:number)=>`${(b/1e12).toLocaleString(undefined,{maximumFractionDigits:1})} TB`;
type Unit="B"|"KB"|"KiB"|"MB"|"MiB"|"GB"|"GiB"|"TB"|"TiB"|"PB"|"PiB"|"EB"|"EiB";
const units:Record<Unit,{label:string;bytes:number;system:"Decimal"|"Binary"}>={B:{label:"Bytes (B)",bytes:1,system:"Decimal"},KB:{label:"Kilobytes (KB)",bytes:1e3,system:"Decimal"},KiB:{label:"Kibibytes (KiB)",bytes:2**10,system:"Binary"},MB:{label:"Megabytes (MB)",bytes:1e6,system:"Decimal"},MiB:{label:"Mebibytes (MiB)",bytes:2**20,system:"Binary"},GB:{label:"Gigabytes (GB)",bytes:1e9,system:"Decimal"},GiB:{label:"Gibibytes (GiB)",bytes:2**30,system:"Binary"},TB:{label:"Terabytes (TB)",bytes:1e12,system:"Decimal"},TiB:{label:"Tebibytes (TiB)",bytes:2**40,system:"Binary"},PB:{label:"Petabytes (PB)",bytes:1e15,system:"Decimal"},PiB:{label:"Pebibytes (PiB)",bytes:2**50,system:"Binary"},EB:{label:"Exabytes (EB)",bytes:1e18,system:"Decimal"},EiB:{label:"Exbibytes (EiB)",bytes:2**60,system:"Binary"}};
const unitKeys=Object.keys(units) as Unit[];
const pretty=(n:number)=>n.toLocaleString(undefined,{maximumFractionDigits:10});
function Field({label,value,onChange,min=0,step=1,suffix}:{label:string;value:number;onChange:(n:number)=>void;min?:number;step?:number;suffix?:string}){return <label className="field"><span>{label}</span><div className="input-wrap"><input aria-label={label} type="number" min={min} step={step} value={value} onChange={e=>onChange(clamp(Number(e.target.value),min))}/>{suffix&&<b>{suffix}</b>}</div></label>}
export default function Home(){
 const [serverBays,setServerBays]=useState(24),[jbods,setJbods]=useState(2),[jbodBays,setJbodBays]=useState(60),[installed,setInstalled]=useState(144),[driveTB,setDriveTB]=useState(22),[spares,setSpares]=useState(4),[raid,setRaid]=useState<Raid>("raidz2"),[width,setWidth]=useState(10),[recordKiB,setRecordKiB]=useState(128),[ashift,setAshift]=useState(12),[swapGiB,setSwapGiB]=useState(2),[fillPct,setFillPct]=useState(80),[convertValue,setConvertValue]=useState("1"),[fromUnit,setFromUnit]=useState<Unit>("TB"),[toUnit,setToUnit]=useState<Unit>("TiB");
 const c=useMemo(()=>{const bays=Math.floor(serverBays+jbods*jbodBays),drives=Math.min(Math.floor(installed),bays),dataDrives=Math.max(0,drives-Math.floor(spares)),vdevWidth=raid==="stripe"?1:Math.max(raid==="mirror"?2:raidInfo[raid].parity+1,Math.floor(width)),vdevs=Math.floor(dataDrives/vdevWidth),leftovers=dataDrives-vdevs*vdevWidth,raw=drives*driveTB*1e12,diskPartition=Math.max(0,driveTB*1e12-swapGiB*GIB-20480-65536),osize=Math.floor(diskPartition/KIB256)*KIB256,usableDisk=Math.max(0,osize-4.5*1024**2);let asize:number,deflate=1;if(raid==="mirror")asize=usableDisk;else{asize=usableDisk*vdevWidth;if(raidInfo[raid].parity>0){const parity=raidInfo[raid].parity,sectors=recordKiB*1024/2**ashift,stripes=Math.ceil(sectors/(vdevWidth-parity)),occupied=sectors+stripes*parity,padded=Math.ceil(occupied/(parity+1))*(parity+1);deflate=Math.floor(sectors/padded*512)/512}}let shift=29;while(shift<34&&asize/2**shift>200)shift++;const metaslab=2**shift,poolSize=Math.floor(asize/metaslab)*metaslab*vdevs,postParity=poolSize*deflate,slop=Math.min(128*GIB,Math.max(128*1024**2,postParity/32)),usable=Math.max(0,postParity-slop);return{bays,drives,vdevWidth,vdevs,leftovers,raw,poolSize,deflate,slop,usable,planned:usable*fillPct/100,shift}},[serverBays,jbods,jbodBays,installed,driveTB,spares,raid,width,recordKiB,ashift,swapGiB,fillPct]);
 const warning=installed>c.bays?`${installed-c.bays} installed drives exceed available bays.`:c.leftovers?`${c.leftovers} data drive${c.leftovers===1?" is":"s are"} outside a complete vdev.`:null;
 const numericConvertValue=Number(convertValue)||0;
 const converted=numericConvertValue*units[fromUnit].bytes/units[toUnit].bytes;
 const swapUnits=()=>{setFromUnit(toUnit);setToUnit(fromUnit)};
 return <main><header><div className="brand"><span className="mark">S</span><span>STORAGE LAB / CAPACITY</span></div><p>OpenZFS planning instrument</p></header>
 <section className="converter"><div className="converter-heading"><span>↔</span><div><p className="eyebrow">QUICK UNIT CONVERTER</p><h2>Decimal in. Binary out.<br/><em>Or any direction you need.</em></h2><p>Drive labels use powers of 1,000. Operating systems and storage tools often report powers of 1,024. Convert between both systems instantly.</p></div></div><div className="converter-tool"><label className="convert-value"><span>VALUE</span><input aria-label="Value to convert" type="number" min="0" step="any" value={convertValue} onChange={e=>setConvertValue(e.target.value)}/></label><label><span>FROM</span><select aria-label="Convert from unit" value={fromUnit} onChange={e=>setFromUnit(e.target.value as Unit)}>{unitKeys.map(k=><option key={k} value={k}>{units[k].label}</option>)}</select><small>{units[fromUnit].system} · {pretty(units[fromUnit].bytes)} bytes</small></label><button type="button" className="swap" onClick={swapUnits} aria-label="Swap conversion units">⇄</button><label><span>TO</span><select aria-label="Convert to unit" value={toUnit} onChange={e=>setToUnit(e.target.value as Unit)}>{unitKeys.map(k=><option key={k} value={k}>{units[k].label}</option>)}</select><small>{units[toUnit].system} · {pretty(units[toUnit].bytes)} bytes</small></label><div className="convert-result" aria-live="polite"><span>RESULT</span><strong>{pretty(converted)}</strong><b>{toUnit}</b><small>{pretty(numericConvertValue)} {fromUnit} = {pretty(converted)} {toUnit}</small></div></div></section>
 <section className="hero"><div><p className="eyebrow">CAPACITY, WITHOUT THE HAND-WAVING</p><h1>Size the server.<br/><em>Know what’s usable.</em></h1><p className="lede">Model a storage server and its JBOD expansion shelves, then see the capacity that survives bays, spares, vdev geometry, parity, padding, metadata allocation, and ZFS slop space.</p></div><div className="hero-stat"><small>PLANNED USABLE</small><strong>{fmt(c.planned)}</strong><span>{fmtTB(c.planned)} at {fillPct}% fill target</span></div></section>
 <div className="workspace"><section className="panel inputs"><div className="panel-title"><span>01</span><div><h2>Hardware envelope</h2><p>Define every slot you can physically populate.</p></div></div><div className="grid three"><Field label="Server drive bays" value={serverBays} onChange={setServerBays}/><Field label="JBOD shelves" value={jbods} onChange={setJbods}/><Field label="Bays per JBOD" value={jbodBays} onChange={setJbodBays}/></div><div className="bay-summary"><span>PHYSICAL BAY MAP</span><div className="bays"><i style={{width:`${Math.min(100,c.bays?c.drives/c.bays*100:0)}%`}}/></div><b>{c.drives} installed / {c.bays} available</b></div><div className="grid three"><Field label="Installed drives" value={installed} onChange={setInstalled}/><Field label="Drive capacity" value={driveTB} onChange={setDriveTB} step={.1} suffix="TB"/><Field label="Hot spares" value={spares} onChange={setSpares}/></div>
 <div className="panel-title second"><span>02</span><div><h2>Pool geometry</h2><p>Arrange installed data drives into top-level vdevs.</p></div></div><div className="grid two"><label className="field"><span>Vdev type</span><select value={raid} onChange={e=>setRaid(e.target.value as Raid)}>{Object.entries(raidInfo).map(([k,x])=><option key={k} value={k}>{x.label}</option>)}</select></label><Field label={raid==="mirror"?"Mirror width":"Drives per vdev"} value={width} onChange={setWidth} min={raid==="mirror"?2:raidInfo[raid].parity+1}/></div><div className="vdev-strip"><div><strong>{c.vdevs}</strong><span>complete vdevs</span></div><div><strong>{c.vdevWidth}</strong><span>drives / vdev</span></div><div><strong>{(c.deflate*100).toFixed(1)}%</strong><span>data efficiency</span></div></div>{warning&&<p className="warning">⚠ {warning}</p>}
 <details><summary>Advanced ZFS assumptions <span>+</span></summary><div className="grid three advanced"><label className="field"><span>Record size</span><select value={recordKiB} onChange={e=>setRecordKiB(Number(e.target.value))}>{[16,32,64,128,256,512,1024].map(n=><option key={n} value={n}>{n} KiB</option>)}</select></label><label className="field"><span>ashift</span><select value={ashift} onChange={e=>setAshift(Number(e.target.value))}><option value="9">9 — 512 B</option><option value="12">12 — 4 KiB</option><option value="13">13 — 8 KiB</option></select></label><Field label="Swap per drive" value={swapGiB} onChange={setSwapGiB} suffix="GiB"/></div></details></section>
 <aside className="panel results"><div className="panel-title"><span>03</span><div><h2>Capacity result</h2><p>Estimated with OpenZFS allocation behavior.</p></div></div><div className="capacity-card"><span>ZFS-REPORTED USABLE</span><strong>{fmt(c.usable)}</strong><small>{fmtTB(c.usable)} decimal</small></div><label className="slider"><span><b>Operational fill target</b><output>{fillPct}%</output></span><input aria-label="Operational fill target" type="range" min="50" max="95" value={fillPct} onChange={e=>setFillPct(Number(e.target.value))}/></label><div className="planned"><span>PLANNED DATA CAPACITY</span><strong>{fmt(c.planned)}</strong><p>Leaves {100-fillPct}% free for performance, snapshots, churn, and growth.</p></div><div className="waterfall"><h3>Capacity waterfall</h3><div><span>Manufacturer raw</span><b>{fmt(c.raw)}</b></div><div><span>Pool allocation</span><b>{fmt(c.poolSize)}</b></div><div><span>Parity + padding</span><b>− {fmt(c.poolSize*(1-c.deflate))}</b></div><div><span>SPA slop reserve</span><b>− {fmt(c.slop)}</b></div></div><div className="formula"><span>CONFIGURATION</span><p>{c.drives} × {driveTB} TB · {spares} spare{spares===1?"":"s"} · {c.vdevs} × {c.vdevWidth}-wide {raidInfo[raid].label}</p><small>Metaslab shift {c.shift} · {recordKiB} KiB records · ashift {ashift}</small></div></aside></div>
 <section className="notes"><div><span>METHOD</span><h2>More than parity arithmetic.</h2></div><p>This estimator follows the allocation model documented by the OpenZFS capacity calculator: decimal drive labels are converted to bytes, partitions and labels are removed, vdev space is rounded into metaslabs, RAIDZ parity and padding use the 1/512 deflate ratio, and SPA slop is reserved. Actual results can vary with platform partitioning, OpenZFS version, special vdevs, dataset properties, compression, and workload.</p><a href="https://jro.io/capacity/" target="_blank" rel="noreferrer">Read the calculation walkthrough ↗</a></section><footer><span>STORAGE LAB</span><p>Planning estimate — validate final designs on representative hardware and your target OpenZFS release.</p></footer></main>}
